### ISSUE TITLE
pre-trained model files

### ISSUE THREAD

**Issue by kangmg** [X1X1010/XequiNet#1]
Thank you for the great work! 

I'm interested in benchmarking the model. Could you please let me know where I can find the pretrained JIT model used in the paper? 

I'm trying to create an ASE calculator but I can't find any JIT model in the repository. 

```python
from xequinet.interface import XeqCalculator

calc = XeqCalculator(model=' jit model ? ')
```

The .pt files in the `xequinet/utils/pre_computed/` folder seem to be element-wise energy data, which results in an error when I try to run `xeqjit -c example.pt`. 

Could you provide guidance on accessing the correct pretrained JIT model file?

**Comment by X1X1010** [comment]
I'm sorry for the late reply. Thank you for your interest in our work. It is true that we do not make our pre-trained models publicly available. You can contact the corresponding author of our work [https://doi.org/10.1021/acs.jctc.4c01151](url). I believe he'd love to share our models.

**Comment by kangmg** [comment]
I will reach out to the corresponding author. Thank you for your guidance.
