### ISSUE TITLE
Add Geometry Optimization Model Support to ASE Calculator

### ISSUE THREAD

**Issue by kangmg** [X1X1010/XequiNet#2]
XeqCalculator currently only supports MD models (with `--md` option), which prevents the use of geometry optimization models (without --md) in ASE.

I've modified the [ASE Calculator](https://github.com/kangmg/XequiNet/blob/master/xequinet/interface/ase_calculator.py) to support both md( with `--md`) and geometry( without `--md`) models while maintaining backwards compatibility.

A [test notebook](https://github.com/kangmg/XequiNet/blob/master/notebook/xequinet_ase.ipynb) demonstrating this functionality can be found here.

Would this enhancement be useful for the project?

**Comment by X1X1010** [comment]
Perfect work. I appreciate it. I'll consider adding this to the branch I'm developing. You can also follow this branch if you're interested https://github.com/X1X1010/XequiNet/tree/yicheng/pre-released
Comments and suggestions are also welcome 😊

**Comment by kangmg** [comment]
Thank you for considering it. I'm looking forward to the new release!
